#!/bin/bash
grep "<" $1.ineq > temp
sed -i 's/),/)/g;s/\(.*\)/\1\&\&/g' temp
tr '\n' ' ' < temp > temp2
sed 's/L(\([^)]*\))/L[\1]/g;s/U(\([^)]*\))/U[\1]/g;s/THETA(\([^)]*\))/THETA[\1]/g;s/"//g;s/{//g;s/}//g;s/ //g' temp2 > temp.mat
grep -o '\(U\|L\|THETA\)\[[^]]*\]' temp.mat | sort | uniq > temp.list
grep -o '\[[^]]*\]' temp.mat | sort | uniq | sed 's/\(.*\)/L\1 < U\1 \&\&/g' >> temp.mat
sed 's/\(.*\)/0 < \1 \&\&/g' temp.list | tr '\n' ' ' >> temp.mat
tr '\n' ' ' < temp.mat > temp.mat2
sed -i 's/&& *$//g' temp.mat2
tr '\n' ','  < temp.list | sed 's/,$//g' >> temp.var
echo 'Print["Parameter Node '$1'"]' > temp.line1
echo 'Print["Defined by inequalities:"]' > temp.line2
sed 's/\(.*\)/Print[\1]/g' temp.mat2 > temp.line3
echo 'Print["A solution to those inequalities:"]' > temp.line4
echo "Print[FindInstance[" > temp.ans
cat temp.mat2 >> temp.ans
echo ",{" >> temp.ans
cat temp.var >> temp.ans
echo "}]]" >> temp.ans
tr '\n' ' ' < temp.ans | sed 's/ //g;s/&&/ \&\& /g' > temp.line5
cat temp.line1
cat temp.line2
cat temp.line3
cat temp.line4
cat temp.line5
rm temp
rm temp2
rm temp.list
rm temp.mat
rm temp.mat2
rm temp.var
rm temp.ans
rm temp.line1
rm temp.line2
rm temp.line3
rm temp.line4
rm temp.line5
