#!/bin/bash
SRC_ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# 1 input  (1 output - 7 outputs)
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,1,1},\"'$1'/1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,2,1},\"'$1'/1_2_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,3,1},\"'$1'/1_3_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,4,1},\"'$1'/1_4_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,5,1},\"'$1'/1_5_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,6,1},\"'$1'/1_6_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{1,7,1},\"'$1'/1_7_1.json\"]"'

# 2 inputs  (1 output - 7 outputs)
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,1,1,1},\"'$1'/2_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,1,2},\"'$1'/2_1_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,2,1,1},\"'$1'/2_2_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,2,2},\"'$1'/2_2_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,3,1,1},\"'$1'/2_3_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,3,2},\"'$1'/2_3_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,4,1,1},\"'$1'/2_4_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,4,2},\"'$1'/2_4_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,5,1,1},\"'$1'/2_5_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,5,2},\"'$1'/2_5_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,6,1,1},\"'$1'/2_6_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,6,2},\"'$1'/2_6_2.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,7,1,1},\"'$1'/2_7_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{2,7,2},\"'$1'/2_7_2.json\"]"'

# 3 inputs  (1 output - 5 outputs)
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,1,1,1,1},\"'$1'/3_1_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,1,1,2},\"'$1'/3_1_1_2.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,1,3},\"'$1'/3_1_3.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,2,1,1,1},\"'$1'/3_2_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,2,1,2},\"'$1'/3_2_1_2.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,2,3},\"'$1'/3_2_3.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,3,1,1,1},\"'$1'/3_3_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,3,1,2},\"'$1'/3_3_1_2.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,3,3},\"'$1'/3_3_3.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,4,1,1,1},\"'$1'/3_4_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,4,1,2},\"'$1'/3_4_1_2.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,4,3},\"'$1'/3_4_3.json\"]"'

$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,5,1,1,1},\"'$1'/3_5_1_1_1.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,5,1,2},\"'$1'/3_5_1_2.json\"]"'
$SRC_ROOT/runMathematica '"Import[\"ComputeParameterGraph.wl\", \"ExpressionList\"]; ComputeCADDatabase[{3,5,3},\"'$1'/3_5_3.json\"]"'
